FROM gettyimages/spark:2.1.0-hadoop-2.7

COPY metrics-influxdb-1.1.8.jar /usr/spark-2.1.0/jars/metrics-influxdb-1.1.8.jar
COPY spark-influx-sink-0.3.12-1-g1a8d6e8.jar /usr/spark-2.1.0/jars/spark-influx-sink-0.3.12-1-g1a8d6e8.jar
COPY metrics.properties /usr/spark-2.1.0/conf/metrics.properties
