apiVersion: extensions/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: influxsrv
  namespace: hyperpilot
  labels:
      app: influxsrv
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: influxsrv
    spec:
      hostname: influxsrv
      volumes:
      - name: influx-data
        hostPath:
            path: /home/ubuntu/influx_data
      containers:
      - name: influxsrv
        image: hyperpilot/influx:1.2.2-restore
        args: ["restore", "%URL"]
        ports:
        - containerPort: 80
          hostPort: 8083
          protocol: TCP
        - containerPort: 8086
          hostPort: 8086
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: influx-data
        resources:
          requests:
            cpu: 2048m
            memory: 4096Mi
