group: edge
sudo: required

language: go
go: 
  - 1.7.1

services: 
  - docker

install:
  - go get -u github.com/golang/lint/golint

before_script:
  - make check

script: 
  - make

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - make docker-build
  - make docker-push
